#!/usr/bin/env bash

FOLDER=$HOME/

openvid () { \
  NAME="$(echo "$(command ls $FOLDER)" | dmenu -c -l 15)" || exit 0
  /usr/bin/mpv "$FOLDER$NAME" >/dev/null 2>&1
}

if [ $# -gt 0 ]; then
  exec /usr/bin/mpv "$@"
else
  openvid
fi
